<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name=Generator content="FastReport http://www.fast-report.com">
<title>dtr</title>
<style type="text/css"><!-- 
.s0-1 { font-style:normal;font-family:Arial;font-size:1px;color:Transparent;background-color:transparent;text-align:Left;vertical-align:Top;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px;}
.s1-1 { font-weight:bold;font-style:normal;font-family:Tw Cen MT;font-size:19px;color:#000040;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s2-1 { font-weight:bold;font-style:normal;font-family:Tw Cen MT;font-size:16px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s3-1 { font-weight:bold;font-style:normal;font-family:Tw Cen MT;font-size:19px;color:#000040;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s4-1 { font-weight:bold;font-style:normal;font-family:Tw Cen MT;font-size:16px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s5-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Right;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;direction:rtl;}
.s6-1 { font-style:normal;font-family:Tw Cen MT Condensed;font-size:16px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s7-1 { font-weight:bold;font-style:normal;font-family:Tw Cen MT Condensed;font-size:16px;color:Black;background-color:transparent;text-align:Left;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s8-1 { font-style:normal;font-family:Arial;font-size:1px;color:Transparent;background-color:transparent;text-align:Left;vertical-align:Top;overflow:hidden;border-collapse: separate;border-bottom:none;border-top:none;border-left-width:3px;border-left-color:Black;border-left-style:double;border-right:none;text-indent:0px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px;}
.s9-1 { font-style:normal;font-family:Arial;font-size:1px;color:Transparent;background-color:transparent;text-align:Left;vertical-align:Top;overflow:hidden;border-collapse: separate;border-bottom:none;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right:none;text-indent:0px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px;}
.s10-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:Gainsboro;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s11-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s12-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s13-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:9px;color:Black;background-color:transparent;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s14-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:Gainsboro;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s15-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s16-1 { font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s17-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s18-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s19-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s20-1 { font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s21-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s22-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s23-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s24-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s25-1 { font-style:normal;font-family:Arial Narrow;font-size:15px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s26-1 { font-style:normal;font-family:Arial Narrow;font-size:15px;color:Black;background-color:transparent;text-align:Justify;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;}
.s27-1 { font-weight:bold;font-style:normal;text-decoration:underline;font-family:Arial Narrow;font-size:15px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s28-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s29-1 { font-weight:bold;font-style:normal;text-decoration:underline;font-family:Arial Narrow;font-size:15px;color:Black;background-color:transparent;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s30-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s31-1 { font-weight:bold;font-style:normal;text-decoration:underline;font-family:Arial Narrow;font-size:16px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s32-1 { font-weight:bold;font-style:normal;text-decoration:underline;font-family:Arial Narrow;font-size:16px;color:Black;background-color:transparent;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s33-1 { font-style:normal;font-family:Tahoma;font-size:11px;color:Transparent;background-color:transparent;text-align:Left;vertical-align:Top;overflow:hidden;border-collapse: separate;border:none;text-indent:0px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px;}
.s34-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s35-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s36-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:9px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s37-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s38-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:9px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s39-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top-width:1px;border-top-color:Black;border-top-style:solid;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s40-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s41-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:Gainsboro;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s42-1 { font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s43-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s44-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s45-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s46-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s47-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s48-1 { font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s49-1 { font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Center;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s50-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s51-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right-width:1px;border-right-color:Black;border-right-style:solid;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s52-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left-width:1px;border-left-color:Black;border-left-style:solid;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s53-1 { font-weight:bold;font-style:normal;font-family:Arial Narrow;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Middle;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
.s54-1 { font-style:normal;font-family:Arial;font-size:13px;color:Black;background-color:transparent;text-align:Left;vertical-align:Top;word-wrap:break-word;overflow:hidden;border-collapse: separate;border-bottom-width:1px;border-bottom-color:Black;border-bottom-style:solid;border-top:none;border-left:none;border-right:none;text-indent:0px;padding-left:2px;padding-right:2px;padding-top:1px;padding-bottom:1px;}
--></style>
</head>
<body bgcolor="#FFFFFF" text="#000000">
<a name="PageN1" style="padding:0;margin:0;font-size:1px;"></a><table width="756px;" border="0" cellspacing="0" cellpadding="0" style="border-collapse:separate;border:none;padding:0;margin:0;table-layout:fixed;" >
<tr style="height: 1px"><td style="boder-collapse:separate;border:none;padding:0;" width="38px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="45px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="31px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="15px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="25px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="22px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="35px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="19px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="38px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="19px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="36px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="31px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="15px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="46px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="15px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="31px;"/><td style="boder-collapse:separate;border:none;padding:0;" width="44px;"/></tr>
<tr style="height:19px;"><td rowspan="2" class="s0-1" style="font-size:1px;" nowrap ></td><td colspan="7" class="s1-1">PARTIDO STATE UNIVERSITY</td></td></td></td><td rowspan="2" class="s0-1" style="font-size:1px;" nowrap ></td><td colspan="8" class="s1-1">PARTIDO STATE UNIVERSITY</td></td></td></tr>
<tr style="height:19px;"><td colspan="7" class="s2-1">Camarines Sur</td></td></td></td><td colspan="8" class="s2-1">Camarines Sur</td></td></td></tr>
<tr style="height:19px;"></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></tr>
<tr style="height:19px;"></td><td colspan="7" class="s3-1">DAILY TIME RECORD</td></td></td></td></td><td colspan="8" class="s3-1">DAILY TIME RECORD</td></td></td></tr>
<tr style="height:19px;"></td><td colspan="7" class="s4-1">August 2024</td></td></td></td></td><td colspan="8" class="s4-1">August 2024</td></td></td></tr>
<tr style="height:19px;"><td colspan="11" class="s5-1">PSU-100903</td><td colspan="11" class="s5-1">PSU-100903</td></tr>
<tr style="height:19px;"><td class="s6-1">Name:</td><td colspan="10" class="s7-1">Enciso, Benjamin Zachary&nbsp;</td><td colspan="2" class="s6-1">Name:</td><td colspan="9" class="s7-1">Enciso, Benjamin Zachary&nbsp;</td></tr>
<tr style="height:19px;"></td><td colspan="10" class="s7-1">CEA</td><td colspan="2" class="s6-1">Division:</td><td colspan="9" class="s7-1">CEA</td></tr>
<tr style="height:19px;"></td><td colspan="10" class="s7-1">Research Assistant</td><td colspan="2" class="s6-1">Position:</td><td colspan="9" class="s7-1">Research Assistant</td></tr>
<tr style="height:19px;"><td colspan="4" class="s6-1">Official Hours for Regular Days:</td><td colspan="7" class="s7-1">8:00-12:00, 1:00-5:00</td><td colspan="5" class="s6-1">Official Hours for Regular Days:</td><td colspan="6" class="s7-1">8:00-12:00, 1:00-5:00</td></tr>
<tr style="height:28px;"><td rowspan="2" class="s34-1">Day</td><td colspan="2" class="s37-1">AM TIME</td><td colspan="3" class="s37-1">PM TIME</td><td colspan="3" class="s37-1">OVERTIME</td><td colspan="2" rowspan="2" class="s38-1">Tardy &amp;<p style="margin-top:0px;margin-bottom:0px;"></p>Undertime</td><td rowspan="2" class="s39-1">Day</td><td colspan="3" class="s37-1">AM TIME</td><td colspan="3" class="s37-1">PM TIME</td><td colspan="3" class="s37-1">OVERTIME</td><td rowspan="2" class="s38-1">Tardy &amp; Undertime</td></tr>
<tr style="height:19px;"><td class="s41-1">IN</td><td class="s41-1">OUT</td><td colspan="2" class="s41-1">IN</td><td class="s41-1">OUT</td><td class="s41-1">IN</td><td colspan="2" class="s41-1">OUT</td><td colspan="2" class="s41-1">IN</td><td class="s41-1">OUT</td><td colspan="2" class="s41-1">IN</td><td class="s41-1">OUT</td><td class="s41-1">IN</td><td colspan="2" class="s41-1">OUT</td></tr>
<tr style="height:19px;"><td class="s42-1">01</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">01</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">02</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">02</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">03</td><td class="s43-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">03</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">04</td><td class="s43-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">04</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">05</td><td class="s43-1">06:30 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:53 pm</td><td class="s44-1">05:14 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">05</td><td colspan="2" class="s44-1">06:30 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:53 pm</td><td class="s44-1">05:14 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">06</td><td class="s43-1">06:22 am</td><td class="s44-1">12:01 pm</td><td colspan="2" class="s44-1">12:48 pm</td><td class="s44-1">05:18 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">06</td><td colspan="2" class="s44-1">06:22 am</td><td class="s44-1">12:01 pm</td><td colspan="2" class="s44-1">12:48 pm</td><td class="s44-1">05:18 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">07</td><td class="s43-1">06:22 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:44 pm</td><td class="s44-1">05:38 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">07</td><td colspan="2" class="s44-1">06:22 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:44 pm</td><td class="s44-1">05:38 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">08</td><td class="s43-1">06:24 am</td><td class="s44-1">12:06 pm</td><td colspan="2" class="s44-1">12:53 pm</td><td class="s44-1">05:24 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">08</td><td colspan="2" class="s44-1">06:24 am</td><td class="s44-1">12:06 pm</td><td colspan="2" class="s44-1">12:53 pm</td><td class="s44-1">05:24 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">09</td><td class="s43-1">06:43 am</td><td class="s44-1">12:05 pm</td><td colspan="2" class="s44-1">12:50 pm</td><td class="s44-1">05:01 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">09</td><td colspan="2" class="s44-1">06:43 am</td><td class="s44-1">12:05 pm</td><td colspan="2" class="s44-1">12:50 pm</td><td class="s44-1">05:01 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">10</td><td class="s43-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">10</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">11</td><td class="s43-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">11</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">12</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">12</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">13</td><td class="s43-1">06:31 am</td><td class="s44-1">12:02 pm</td><td colspan="2" class="s44-1">12:36 pm</td><td class="s44-1">05:14 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">13</td><td colspan="2" class="s44-1">06:31 am</td><td class="s44-1">12:02 pm</td><td colspan="2" class="s44-1">12:36 pm</td><td class="s44-1">05:14 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">14</td><td class="s43-1">06:31 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:45 pm</td><td class="s44-1">05:03 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">14</td><td colspan="2" class="s44-1">06:31 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:45 pm</td><td class="s44-1">05:03 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">15</td><td class="s43-1">06:42 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:58 pm</td><td class="s44-1">05:30 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">15</td><td colspan="2" class="s44-1">06:42 am</td><td class="s44-1">12:00 pm</td><td colspan="2" class="s44-1">12:58 pm</td><td class="s44-1">05:30 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">16</td><td class="s43-1">06:18 am</td><td class="s44-1">12:01 pm</td><td colspan="2" class="s44-1">12:51 pm</td><td class="s44-1">05:28 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">16</td><td colspan="2" class="s44-1">06:18 am</td><td class="s44-1">12:01 pm</td><td colspan="2" class="s44-1">12:51 pm</td><td class="s44-1">05:28 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">17</td><td class="s43-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">17</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">18</td><td class="s43-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">18</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">19</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">19</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">20</td><td class="s43-1">06:24 am</td><td class="s44-1">11:54 am</td><td colspan="2" class="s44-1">12:27 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">20</td><td colspan="2" class="s44-1">06:24 am</td><td class="s44-1">11:54 am</td><td colspan="2" class="s44-1">12:27 pm</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">21</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">21</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">22</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">22</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">23</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">23</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">24</td><td class="s43-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">24</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">25</td><td class="s43-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">25</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td colspan="2" class="s44-1">SUN</td><td class="s44-1">SUN</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">26</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">26</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">27</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">27</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">28</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">28</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">29</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">29</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">30</td><td class="s43-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">30</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s42-1">31</td><td class="s43-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s46-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s47-1" style="font-size:1px;">&nbsp;</td><td class="s49-1">31</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td colspan="2" class="s44-1">SAT</td><td class="s44-1">SAT</td><td class="s44-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s44-1" style="font-size:1px;">&nbsp;</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:19px;"><td class="s52-1" style="font-size:1px;">&nbsp;</td><td colspan="2" class="s53-1">Tardy= 0</td><td colspan="3" class="s53-1">Under= 0</td><td colspan="3" class="s53-1">Absent= 0</td><td colspan="2" class="s51-1" style="font-size:1px;">&nbsp;</td><td class="s54-1" style="font-size:1px;">&nbsp;</td><td colspan="3" class="s53-1">Tardy= 0</td><td colspan="3" class="s53-1">Under= 0</td><td colspan="3" class="s53-1">Absent= 0</td><td class="s51-1" style="font-size:1px;">&nbsp;</td></tr>
<tr style="height:83px;"><td colspan="11" class="s26-1">I Certify on my honor that the above is true and correct report of the hours of work performed, record of which was made daily of the time of arrival and departure from office.</td><td colspan="11" class="s26-1">I Certify on my honor that the above is true and correct report of the hours of work performed, record of which was made daily of the time of arrival and departure from office.</td></tr>
<tr style="height:26px;"><td colspan="11" class="s27-1">Benjamin Zachary&nbsp;&nbsp;C. Enciso</td><td colspan="11" class="s29-1">Benjamin Zachary&nbsp;&nbsp;C. Enciso</td></tr>
<tr style="height:24px;"><td colspan="11" class="s28-1">Employee Signature</td><td colspan="11" class="s30-1">Employee Signature</td></tr>
<tr style="height:19px;"><td colspan="11" class="s25-1">Verified as to the prescribed office hours.</td><td colspan="11" class="s25-1">Verified as to the prescribed office hours.</td></tr>
<tr style="height:28px;"></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></td></tr>
<tr style="height:24px;"><td colspan="11" class="s31-1">__________________________________</td><td colspan="11" class="s32-1">__________________________________</td></tr>
<tr style="height:24px;"><td colspan="11" class="s30-1">Supervisor / Dept. Head Signature</td><td colspan="11" class="s30-1">Supervisor / Dept. Head Signature</td></tr>
</table>
</body>
</html>
